{% set name = "pycdf" %}
{% set version = "0.1.4" %}
{% set sha256 = "ef29025b9ac04b02b610803fb6abc84307ae34137742fd6f0c738f9315f0296c" %}


package:
   name: {{ name }} 
   version: {{ version }} 
   
source:
   fn:  cdf-dist-cdf.tar.gz
   url: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_1/cdf-dist-cdf.tar.gz
   sha256: {{ sha256 }}
   patches:
      - 0001_add_pycdf.patch
      - 0002_build_libonly.patch
      - 0003_macos_make.patch
      - 0004_nmake_file.patch
      - 0005_zlib_unistd.patch

build:
   # This is the zeroth build
   number: 0
   
requirements:
   build:
      - {{ compiler('c') }}
      - python
      - numpy
#      - numpy <=1.17.3   # Higer level version broken on MacOS!
      
   host:
      - python
      - numpy
#      - numpy <=1.17.3   # Anaconda abandoned old Mac's, time
#                         # to return the favor and use pip
                  
   run:
      - python
      - numpy
#      - numpy <=1.17.3   # The last version that doesn't require
#                         # AVX CPU features
      
test:
   imports:
      - pycdf

about:
   home: https://github.com/cpiker/condaCDF
   license: Custom/Combined
   license_file: ../LICENSE
   summary: pycdf and libcdf.so as a stand alone package
